api_platform:
    mapping:
            paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            bearerAuth:
                name: Authorization
                type: header
    openapi:
        swagger_ui_extra_configuration:
            components:
                securitySchemes:
                    bearerAuth:
                        type: http
                        scheme: bearer
                        bearerFormat: JWT
            security:
                - bearerAuth: []